import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export const metadata: Metadata = {
  title: {
    default: 'Local Eats',
    template: '%s | Local Eats',
  },
  description: 'Discover the best local food businesses around you',
  keywords: ['culinary', 'local food', 'restaurant', 'warung', 'Medan'],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        {/* <Navbar /> */}
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
